# Dynamic DockerFile application file for abcdesktop.io generated by https://github.com/abcdesktopio/abcdesktopio/oc.apps/make.js
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# Dockerfile claude-desktop is generated at Wed Jun 11 2025 17:02:16 GMT-0600 (Mountain Daylight Time)
# platforms=linux/amd64,linux/arm64
#
ARG TAG=dev
FROM abcdesktopio/oc.template.gtk:$TAG
USER root
LABEL oc.icon="claude-desktop.svg"
LABEL oc.icondata="PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+CiAgPGRlZnM+CiAgICA8bGluZWFyR3JhZGllbnQgaWQ9ImNsYXVkZUdyYWRpZW50IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj4KICAgICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6I0Q5Nzc1NztzdG9wLW9wYWNpdHk6MSIgLz4KICAgICAgPHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojQjg1NDQ1O3N0b3Atb3BhY2l0eToxIiAvPgogICAgPC9saW5lYXJHcmFkaWVudD4KICA8L2RlZnM+CiAgPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTYiIGZpbGw9InVybCgjY2xhdWRlR3JhZGllbnQpIi8+CiAgPHBhdGggZD0iTTMyIDE2Yy04LjggMC0xNiA3LjItMTYgMTZzNy4yIDE2IDE2IDE2IDE2LTcuMiAxNi0xNi03LjItMTYtMTYtMTZ6bTAgNGM2LjYgMCAxMiA1LjQgMTIgMTJzLTUuNCAxMi0xMiAxMi0xMi01LjQtMTItMTIgNS40LTEyIDEyLTEyeiIgZmlsbD0id2hpdGUiIG9wYWNpdHk9IjAuOSIvPgogIDx0ZXh0IHg9IjMyIiB5PSIzOCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjIwIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0id2hpdGUiPkFJPC90ZXh0Pgo8L3N2Zz4K"
LABEL oc.keyword="claude-desktop,claude,ai,assistant,anthropic,chat,llm,artificial intelligence"
LABEL oc.cat="utilities"
LABEL oc.desktopfile="claude-desktop.desktop"
LABEL oc.launch="claude.Claude"
LABEL oc.template="abcdesktopio/oc.template.gtk"
LABEL oc.name="claude-desktop"
LABEL oc.displayname="Claude Desktop"
LABEL oc.path="/opt/Claude/claude"
LABEL oc.type=app
ENV APPNAME "claude-desktop"
ENV APPBIN "/opt/Claude/claude"
USER root
RUN mkdir -p /var/secrets/abcdesktop/localaccount
RUN for f in passwd shadow group gshadow ; do if [ -f /etc/$f ] ; then  cp /etc/$f /var/secrets/abcdesktop/localaccount; rm -f /etc/$f; ln -s /var/secrets/abcdesktop/localaccount/$f /etc/$f; fi; done
USER balloon
CMD [ "/composer/appli-docker-entrypoint.sh" ]
